"""Compatibility exports from minio.minioadmin (minio 7.2.20)."""
from minio.minioadmin import (
    Any as Any,
    BaseHTTPResponse as BaseHTTPResponse,
    DictType as DictType,
    Enum as Enum,
    HTTPHeaderDict as HTTPHeaderDict,
    MinioAdmin as MinioAdmin,
    MinioAdminException as MinioAdminException,
    Optional as Optional,
    PeerInfo as PeerInfo,
    PeerSite as PeerSite,
    PoolManager as PoolManager,
    Provider as Provider,
    Retry as Retry,
    SiteReplicationStatusOptions as SiteReplicationStatusOptions,
    TextIO as TextIO,
    Timeout as Timeout,
    Tuple as Tuple,
    absolute_import as absolute_import,
    annotations as annotations,
    cast as cast,
    certifi as certifi,
    decrypt as decrypt,
    encrypt as encrypt,
    headers_to_strings as headers_to_strings,
    json as json,
    os as os,
    queryencode as queryencode,
    sha256_hash as sha256_hash,
    sign_v4_s3 as sign_v4_s3,
    time as time,
    timedelta as timedelta,
    unique as unique,
    url_replace as url_replace,
    urlunsplit as urlunsplit,
)

__all__ = ['Any', 'BaseHTTPResponse', 'DictType', 'Enum', 'HTTPHeaderDict', 'MinioAdmin', 'MinioAdminException', 'Optional', 'PeerInfo', 'PeerSite', 'PoolManager', 'Provider', 'Retry', 'SiteReplicationStatusOptions', 'TextIO', 'Timeout', 'Tuple', 'absolute_import', 'annotations', 'cast', 'certifi', 'decrypt', 'encrypt', 'headers_to_strings', 'json', 'os', 'queryencode', 'sha256_hash', 'sign_v4_s3', 'time', 'timedelta', 'unique', 'url_replace', 'urlunsplit']
