"""Compatibility exports from minio.replicationconfig (minio 7.2.20)."""
from minio.replicationconfig import (
    A as A,
    ABC as ABC,
    AccessControlTranslation as AccessControlTranslation,
    B as B,
    BaseRule as BaseRule,
    C as C,
    D as D,
    DISABLED as DISABLED,
    DeleteMarkerReplication as DeleteMarkerReplication,
    Destination as Destination,
    E as E,
    ET as ET,
    Element as Element,
    EncryptionConfig as EncryptionConfig,
    EventThreshold as EventThreshold,
    ExistingObjectReplication as ExistingObjectReplication,
    F as F,
    Filter as Filter,
    G as G,
    H as H,
    I as I,
    J as J,
    Metrics as Metrics,
    Optional as Optional,
    ReplicationConfig as ReplicationConfig,
    ReplicationTime as ReplicationTime,
    ReplicationTimeValue as ReplicationTimeValue,
    Rule as Rule,
    SourceSelectionCriteria as SourceSelectionCriteria,
    SseKmsEncryptedObjects as SseKmsEncryptedObjects,
    Status as Status,
    SubElement as SubElement,
    Time as Time,
    Type as Type,
    TypeVar as TypeVar,
    absolute_import as absolute_import,
    annotations as annotations,
    cast as cast,
    check_status as check_status,
    dataclass as dataclass,
    find as find,
    findall as findall,
    findtext as findtext,
)

__all__ = ['A', 'ABC', 'AccessControlTranslation', 'B', 'BaseRule', 'C', 'D', 'DISABLED', 'DeleteMarkerReplication', 'Destination', 'E', 'ET', 'Element', 'EncryptionConfig', 'EventThreshold', 'ExistingObjectReplication', 'F', 'Filter', 'G', 'H', 'I', 'J', 'Metrics', 'Optional', 'ReplicationConfig', 'ReplicationTime', 'ReplicationTimeValue', 'Rule', 'SourceSelectionCriteria', 'SseKmsEncryptedObjects', 'Status', 'SubElement', 'Time', 'Type', 'TypeVar', 'absolute_import', 'annotations', 'cast', 'check_status', 'dataclass', 'find', 'findall', 'findtext']
