"""Compatibility exports from minio.select (minio 7.2.20)."""
from minio.select import (
    ABC as ABC,
    BytesIO as BytesIO,
    COMPRESSION_TYPE_BZIP2 as COMPRESSION_TYPE_BZIP2,
    COMPRESSION_TYPE_GZIP as COMPRESSION_TYPE_GZIP,
    COMPRESSION_TYPE_NONE as COMPRESSION_TYPE_NONE,
    CSVInputSerialization as CSVInputSerialization,
    CSVOutputSerialization as CSVOutputSerialization,
    ET as ET,
    Element as Element,
    FILE_HEADER_INFO_IGNORE as FILE_HEADER_INFO_IGNORE,
    FILE_HEADER_INFO_NONE as FILE_HEADER_INFO_NONE,
    FILE_HEADER_INFO_USE as FILE_HEADER_INFO_USE,
    InputSerialization as InputSerialization,
    JSONInputSerialization as JSONInputSerialization,
    JSONOutputSerialization as JSONOutputSerialization,
    JSON_TYPE_DOCUMENT as JSON_TYPE_DOCUMENT,
    JSON_TYPE_LINES as JSON_TYPE_LINES,
    MinioException as MinioException,
    Optional as Optional,
    OutputSerialization as OutputSerialization,
    ParquetInputSerialization as ParquetInputSerialization,
    QUOTE_FIELDS_ALWAYS as QUOTE_FIELDS_ALWAYS,
    QUOTE_FIELDS_ASNEEDED as QUOTE_FIELDS_ASNEEDED,
    SelectObjectReader as SelectObjectReader,
    SelectRequest as SelectRequest,
    Stats as Stats,
    SubElement as SubElement,
    absolute_import as absolute_import,
    abstractmethod as abstractmethod,
    crc32 as crc32,
    dataclass as dataclass,
    findtext as findtext,
)

__all__ = ['ABC', 'BytesIO', 'COMPRESSION_TYPE_BZIP2', 'COMPRESSION_TYPE_GZIP', 'COMPRESSION_TYPE_NONE', 'CSVInputSerialization', 'CSVOutputSerialization', 'ET', 'Element', 'FILE_HEADER_INFO_IGNORE', 'FILE_HEADER_INFO_NONE', 'FILE_HEADER_INFO_USE', 'InputSerialization', 'JSONInputSerialization', 'JSONOutputSerialization', 'JSON_TYPE_DOCUMENT', 'JSON_TYPE_LINES', 'MinioException', 'Optional', 'OutputSerialization', 'ParquetInputSerialization', 'QUOTE_FIELDS_ALWAYS', 'QUOTE_FIELDS_ASNEEDED', 'SelectObjectReader', 'SelectRequest', 'Stats', 'SubElement', 'absolute_import', 'abstractmethod', 'crc32', 'dataclass', 'findtext']
