"""Compatibility exports from minio.credentials.providers (minio 7.2.20)."""
from minio.credentials.providers import (
    ABC as ABC,
    AWSConfigProvider as AWSConfigProvider,
    AssumeRoleProvider as AssumeRoleProvider,
    BaseHTTPResponse as BaseHTTPResponse,
    Callable as Callable,
    CertificateIdentityProvider as CertificateIdentityProvider,
    ChainedProvider as ChainedProvider,
    ClientGrantsProvider as ClientGrantsProvider,
    Credentials as Credentials,
    ET as ET,
    EnvAWSProvider as EnvAWSProvider,
    EnvMinioProvider as EnvMinioProvider,
    IamAwsProvider as IamAwsProvider,
    LdapIdentityProvider as LdapIdentityProvider,
    MinioClientConfigProvider as MinioClientConfigProvider,
    Optional as Optional,
    Path as Path,
    PoolManager as PoolManager,
    Provider as Provider,
    Retry as Retry,
    StaticProvider as StaticProvider,
    WebIdentityClientGrantsProvider as WebIdentityClientGrantsProvider,
    WebIdentityProvider as WebIdentityProvider,
    abstractmethod as abstractmethod,
    annotations as annotations,
    cast as cast,
    certifi as certifi,
    configparser as configparser,
    find as find,
    findtext as findtext,
    from_iso8601utc as from_iso8601utc,
    ipaddress as ipaddress,
    json as json,
    os as os,
    parse_url as parse_url,
    re as re,
    sha256_hash as sha256_hash,
    sign_v4_sts as sign_v4_sts,
    socket as socket,
    sys as sys,
    time as time,
    timedelta as timedelta,
    to_amz_date as to_amz_date,
    url_replace as url_replace,
    urlencode as urlencode,
    urlsplit as urlsplit,
    urlunsplit as urlunsplit,
    utcnow as utcnow,
)

__all__ = ['ABC', 'AWSConfigProvider', 'AssumeRoleProvider', 'BaseHTTPResponse', 'Callable', 'CertificateIdentityProvider', 'ChainedProvider', 'ClientGrantsProvider', 'Credentials', 'ET', 'EnvAWSProvider', 'EnvMinioProvider', 'IamAwsProvider', 'LdapIdentityProvider', 'MinioClientConfigProvider', 'Optional', 'Path', 'PoolManager', 'Provider', 'Retry', 'StaticProvider', 'WebIdentityClientGrantsProvider', 'WebIdentityProvider', 'abstractmethod', 'annotations', 'cast', 'certifi', 'configparser', 'find', 'findtext', 'from_iso8601utc', 'ipaddress', 'json', 'os', 'parse_url', 're', 'sha256_hash', 'sign_v4_sts', 'socket', 'sys', 'time', 'timedelta', 'to_amz_date', 'url_replace', 'urlencode', 'urlsplit', 'urlunsplit', 'utcnow']
